<!-- DO NOT EDIT THIS FILE-->
		<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->
	
		<html>
		   <?php include 'partials/header.php';?>
		   <body class=" pi">
		      <?php include 'partials/navbar.php';?>
		      <section class="main-section">
		         <div class="container">
		            <div class="row">
		               <div class="col-md-12 col-sm-6 col-xs-12">
		                  <div class="col-md-6 col-xs-12">
		                     <div class="intern-block border-blue">
		                        <img src="https://res.cloudinary.com/diubyoojw/image/upload/v1554460404/IMG_20181028_100531.jpg" alt="James Dayo">
		                        <h6>James Dayo</h6>
		                        <p>Front-end Developer</p>
		                        <ul class="list">
		                           <li><a href="https://twitter.com/dea1j" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
		                           <li><a href="https://github.com/dea1j" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
		                           <li><a href="https://medium.com/@dea1j" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
		                        </ul>
		                     </div>
		                  </div>
		                  <div class="col-md-6 col-xs-12 align-items-center">
		                     <div class="intern-bio border-blue">
		                        <h6>About me</h6>
		                        <p>I'm very interested in tech and take responsibility for my personal development</p>
		                        <p>My best quote is "Keep moving forward" and each time i remember this, i get my strength to improve my self.</p>
		                        <br />
		                        <h6>Skills</h6>
		                        <p>Javascript | CSS | HTML</p>
		                     </div>
		                  </div>
		               </div>
		            </div>
		         </div>
		         </div>
		      </section>
		   </body>
		   <?php include 'partials/footer.php';?>
		</html>